import React, { useState, useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import { FaArrowLeft, FaDownload, FaCheckCircle, FaLeaf, FaSpinner } from "react-icons/fa";
import jsPDF from "jspdf";
import config from "../config";

const ReportDetail = () => {
  const { id } = useParams();
  const [report, setReport]   = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState("");

  useEffect(() => {
    fetchReport();
  }, [id]);

  const fetchReport = async () => {
    try {
      const token    = localStorage.getItem("token");
      const response = await fetch(`config.API_URL/reports/${id}`, {
        headers: { "Authorization": `Bearer ${token}` },
      });
      const data = await response.json();
      if (data.success) {
        setReport(data.report);
      } else {
        setError("Report not found.");
      }
    } catch {
      setError("Server error. Make sure backend is running.");
    }
    setLoading(false);
  };

  const downloadReport = () => {
    if (!report) return;
    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.setTextColor(22, 163, 74);
    doc.text("FasalAI Disease Report", 20, 20);

    doc.setDrawColor(22, 163, 74);
    doc.line(20, 25, 190, 25);

    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(`Disease: ${report.disease}`, 20, 40);
    doc.text(`Crop: ${report.cropType}`, 20, 50);
    doc.text(`Confidence: ${report.confidence}%`, 20, 60);
    doc.text(`Severity: ${report.severity}`, 20, 70);
    doc.text(`Date: ${new Date(report.createdAt).toLocaleDateString()}`, 20, 80);

    doc.setFontSize(14);
    doc.setTextColor(22, 163, 74);
    doc.text("Treatment Plan:", 20, 100);
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    report.treatment.forEach((t, i) => {
      const lines = doc.splitTextToSize(`${i + 1}. ${t}`, 170);
      doc.text(lines, 20, 112 + (i * 14));
    });

    const preventionY = 112 + (report.treatment.length * 14) + 10;
    doc.setFontSize(14);
    doc.setTextColor(22, 163, 74);
    doc.text("Prevention Tips:", 20, preventionY);
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    report.prevention.forEach((p, i) => {
      const lines = doc.splitTextToSize(`${i + 1}. ${p}`, 170);
      doc.text(lines, 20, preventionY + 12 + (i * 14));
    });

    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by FasalAI — Smart Crop Advisory System", 20, 285);
    doc.save(`FasalAI-${report.disease}-Report.pdf`);
  };

  if (loading) return (
    <div className="min-h-screen flex items-center justify-center">
      <FaSpinner className="animate-spin text-primary-500 text-4xl" />
    </div>
  );

  if (error) return (
    <div className="min-h-screen flex items-center justify-center">
      <div className="text-center">
        <p className="text-red-500 mb-4">{error}</p>
        <Link to="/history" className="btn-primary">Back to History</Link>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen bg-gray-50 pt-24 pb-16">
      <div className="max-w-3xl mx-auto px-6 space-y-6">

        <Link to="/history" className="inline-flex items-center gap-2 text-primary-600 hover:underline text-sm font-medium">
          <FaArrowLeft /> Back to History
        </Link>

        {/* Header */}
        <div className="bg-white rounded-3xl shadow-md p-8">
          <div className="flex justify-between items-start flex-wrap gap-4">
            <div>
              <p className="text-sm text-gray-400 mb-1">
                Report · {new Date(report.createdAt).toLocaleDateString()}
              </p>
              <h1 className="font-display text-3xl font-bold text-gray-900">{report.disease}</h1>
              <p className="text-gray-500 mt-1">{report.cropType}</p>
            </div>
            <div className="text-center">
              <div className="text-4xl font-display font-bold text-red-500">{report.confidence}%</div>
              <div className="text-xs text-gray-400">Confidence</div>
            </div>
          </div>

          {/* Image */}
          {report.imageUrl && (
            <img src={report.imageUrl} alt={report.disease}
              className="w-full max-h-64 object-cover rounded-2xl mt-6" />
          )}

          {report.description && (
            <div className="mt-4 bg-gray-50 rounded-xl p-4">
              <p className="text-sm text-gray-500 font-medium mb-1">Description:</p>
              <p className="text-gray-700 text-sm italic">"{report.description}"</p>
            </div>
          )}
        </div>

        {/* Treatment */}
        <div className="bg-white rounded-3xl shadow-md p-8">
          <h2 className="font-display text-xl font-bold text-gray-900 mb-5">💊 Treatment Plan</h2>
          <ul className="space-y-3">
            {report.treatment.map((t, i) => (
              <li key={i} className="flex items-start gap-3">
                <FaCheckCircle className="text-primary-500 mt-0.5 flex-shrink-0" />
                <span className="text-gray-600 text-sm leading-relaxed">{t}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Prevention */}
        <div className="bg-primary-50 rounded-3xl shadow-md p-8">
          <h2 className="font-display text-xl font-bold text-gray-900 mb-5">🛡️ Prevention</h2>
          <ul className="space-y-3">
            {report.prevention.map((p, i) => (
              <li key={i} className="flex items-start gap-3">
                <FaLeaf className="text-primary-500 mt-0.5 flex-shrink-0" />
                <span className="text-gray-600 text-sm leading-relaxed">{p}</span>
              </li>
            ))}
          </ul>
        </div>

        <button onClick={downloadReport}
          className="btn-primary w-full flex items-center justify-center gap-2">
          <FaDownload /> Download Full Report (PDF)
        </button>

      </div>
    </div>
  );
};

export default ReportDetail;
