import React from "react";

const sections = [
  {
    title: "1. Acceptance of terms",
    body: `By using FasalAI, you agree to these terms. If you don't agree, please
don't use the app. These terms may be updated as the project evolves.`,
  },
  {
    title: "2. What FasalAI is",
    body: `FasalAI is a final year software engineering project that provides
AI-assisted crop advisory features, including disease detection from
photos, weather-based risk alerts, and a chatbot for farming questions.`,
  },
  {
    title: "3. Not a substitute for expert advice",
    body: `Predictions and recommendations from FasalAI are generated by an AI model
and are intended to support, not replace, guidance from a qualified
agronomist or agricultural expert. Always use your own judgment, especially
for decisions with significant cost or risk.`,
  },
  {
    title: "4. Accuracy",
    body: `While we aim for high accuracy, disease detection and weather predictions
are not guaranteed to be correct in every case. FasalAI is provided "as is"
without warranties of any kind.`,
  },
  {
    title: "5. Your responsibilities",
    body: `You agree to use the app only for its intended purpose, to provide accurate
information where required, and not to misuse, reverse-engineer, or attempt
to disrupt the service.`,
  },
  {
    title: "6. Account & content",
    body: `You're responsible for keeping your account credentials secure. Photos and
messages you submit remain yours, but you grant us permission to process
them in order to provide the service and improve model accuracy.`,
  },
  {
    title: "7. Limitation of liability",
    body: `As a non-commercial academic project, FasalAI and its team are not liable
for crop losses, financial damages, or other outcomes resulting from
reliance on the app's predictions or advice.`,
  },
  {
    title: "8. Contact",
    body: `Questions about these terms can be sent to support@fasalai.com.`,
  },
];

const Terms = () => (
  <div className="min-h-screen bg-gray-50">
    <div className="bg-[#0B2B1E] text-white">
      <div className="max-w-3xl mx-auto px-6 py-16 text-center">
        <h1 className="font-display font-bold text-3xl sm:text-4xl mb-3">
          Terms of Service
        </h1>
        <p className="text-green-200/70 text-sm">Last updated: July 2026</p>
      </div>
    </div>

    <div className="max-w-3xl mx-auto px-6 py-14">
      <p className="text-gray-600 leading-relaxed mb-10">
        These terms govern your use of FasalAI. Please read them carefully.
        FasalAI is an academic final year project, and these terms are written
        to reflect that scope.
      </p>

      <div className="space-y-8">
        {sections.map((s) => (
          <div key={s.title}>
            <h2 className="font-semibold text-gray-900 text-lg mb-2">{s.title}</h2>
            <p className="text-gray-600 text-sm leading-relaxed whitespace-pre-line">
              {s.body}
            </p>
          </div>
        ))}
      </div>
    </div>
  </div>
);

export default Terms;
